# Generated by Django 3.2.6 on 2021-08-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('about_author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=17)),
                ('publication_year', models.DateTimeField()),
                ('edition', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quant_in_stock', models.BigIntegerField()),
                ('language', models.CharField(max_length=2)),
                ('weight', models.CharField(max_length=4)),
                ('pages', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(to='books.Authors')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publisher')),
                ('tags', models.ManyToManyField(to='books.Tags')),
            ],
        ),
    ]
