# Generated by Django 3.2.6 on 2021-08-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210824_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='image_ppoi_authors',
            new_name='image_ppoi',
        ),
        migrations.RenameField(
            model_name='bookimage',
            old_name='image_ppoi_BookImage',
            new_name='image_ppoi',
        ),
    ]
