# Generated by Django 3.2.6 on 2021-08-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210824_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='image_ppoi',
            new_name='image_ppoi_author',
        ),
        migrations.RenameField(
            model_name='bookimage',
            old_name='image_ppoi',
            new_name='image_ppoi_bookimage',
        ),
    ]
