# Generated by Django 3.2.6 on 2021-08-24 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210823_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 20, 16, 45, 412496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
