# Generated by Django 3.2.6 on 2021-08-24 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210824_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 20, 17, 37, 33352, tzinfo=utc)),
        ),
    ]
