# Generated by Django 3.2.6 on 2021-08-24 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210824_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_ppoi',
            new_name='image_ppoi_customuser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 20, 31, 20, 716650, tzinfo=utc)),
        ),
    ]
