# Generated by Django 3.2.6 on 2021-08-24 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210824_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 20, 33, 53, 464506, tzinfo=utc)),
        ),
    ]
