# Generated by Django 3.2.6 on 2021-08-24 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 20, 16, 45, 419010, tzinfo=utc)),
        ),
    ]
