# Generated by Django 3.2.6 on 2021-08-24 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 20, 17, 37, 33352, tzinfo=utc)),
        ),
    ]
