# Generated by Django 3.2.6 on 2021-08-24 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
