# Generated by Django 3.2.6 on 2021-08-26 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210826_1409'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='orders.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(related_name='order_book', through='orders.OrderBook', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderBook_book', to='books.book'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderBook_order', to='orders.order'),
        ),
    ]
